/** Stable `extensions.code` values clients can branch on. */
export const ErrorCode = {
  BAD_USER_INPUT: 'BAD_USER_INPUT',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  EMPLOYEE_REQUIRED: 'EMPLOYEE_REQUIRED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
} as const;
