import { describe, expect, it } from 'vitest';
import { findAttribution } from './attribution.js';

describe('findAttribution', () => {
  it('returns no matches for a plain conventional commit message', () => {
    const message = 'feat(orders): add state machine\n\nImplements OPEN -> IN_PROGRESS -> COMPLETE.';
    expect(findAttribution(message)).toEqual([]);
  });

  it.each([
    'Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>',
    'co-authored-by: Jane Doe <jane@example.com>',
    '  Co-authored-by: someone',
  ])('flags a Co-Authored-By trailer: %s', (line) => {
    expect(findAttribution(`chore: x\n\n${line}`)).toEqual([line.trim()]);
  });

  it.each([
    '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
    'Generated with Claude Code',
    'Generated by ChatGPT',
    'generated with GitHub Copilot',
  ])('flags an AI "Generated with/by" footer: %s', (line) => {
    expect(findAttribution(`Body text.\n\n${line}\n`)).toEqual([line.trim()]);
  });

  it('flags a Signed-off-by trailer that names an AI tool or bot', () => {
    const line = 'Signed-off-by: Claude <noreply@anthropic.com>';
    expect(findAttribution(`fix: y\n\n${line}`)).toEqual([line]);
  });

  it('allows a human Signed-off-by trailer', () => {
    expect(findAttribution('fix: y\n\nSigned-off-by: Jane Doe <jane@example.com>')).toEqual([]);
  });

  it('does not flag prose that merely mentions generation', () => {
    const body = 'The schema is generated with codegen.\nGenerated with `yarn codegen` from schema.gql.';
    expect(findAttribution(body)).toEqual([]);
  });

  it('reports every offending line', () => {
    const body =
      'Summary\n\nCo-Authored-By: A <a@x>\n🤖 Generated with [Claude Code](https://claude.com/claude-code)';
    expect(findAttribution(body)).toHaveLength(2);
  });
});
